### ISSUE TITLE
Uncaught EvalError

### ISSUE THREAD

**Issue by mflux** [mattdesl/indexof-property#1]
When using this lib in browser (via BMFont), after rollup and used as a node module:

    node_modules\datguivr\build\node_modules\datguivr\node_modules\indexof-property\index.js:5 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://www.youtube.com https://s.ytimg.com *.googleanalytics.com *.google-analytics.com ajax.googleapis.com *.gstatic.com use.typekit.net https://use.typekit.net".

I'm not entirely understanding this error since in usual cases including datguivr (which uses bmfont, which uses indexof-property) it will work correctly. Is this something to do with the security settings of the server which is running my test?

**Comment by mflux** [comment]
Yeah. Upon further inspection, this script is prevented from running due to "unsafe-eval" Django policy for our server. That's really unfortunate. Any way to rewrite this module to not use evaluation?

**Comment by mattdesl** [comment]
Yup totally ok with a rewrite. Also I could probably update bmfont text stuff to get rid of this 😊

**Comment by mattdesl** [comment]
Deprecated this module and fixed it upstream in `layout-bmfont-text` as a patch. Should be fixed next time you install `three-bmfont-text`. :smile:
